[package]
name = "color-density"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
lazy_static = "1.4.0"
rand = "0.8.5"
rustc-hash = "1.1.0"
tgraph = "0.2.2"
threadpool = "1.8.1"
